name = "ALLIANCE_MODULE"
description = "Manage bot access via members of multiple orgs"
version = "0.2.0"
github = "Nadybot/ALLIANCE_MODULE"
author = "Nadyita"
bot_type = "Nadybot"
bot_version = "^6.0.0-alpha.1"
